# Generated by Django 4.2.1 on 2023-05-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_menuvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='votes',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
