# Generated by Django 4.2.1 on 2023-05-08 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_menu_excel_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='excel_file',
        ),
    ]
