# Generated by Django 4.2.1 on 2023-05-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_menuvote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuVote',
        ),
    ]
